# TEMPORARY FILE FOR LOCAL TESTING - DO NOT COMMIT
# This file uses local components for development and testing
# Copy from example_opentherm.yaml and modify the external_components section

# Example configuration for OpenTherm Gateway
# Platform: ESP8266 (NodeMCU or similar)
# Author: Your Name
# Repository: https://github.com/sakrut/ESPHome-OpenTherm-Gateway

substitutions:
  device_name: opentherm_gateway
  friendly_name: OpenTherm Gateway

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "ESPHome OpenTherm Gateway for integrating with heating boilers"

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: VERBOSE
  logs:
    opentherm.component: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "YOUR_OTA_PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${friendly_name} Fallback AP"
    password: "YOUR_AP_PASSWORD"

captive_portal:

# LOCAL TESTING - uses local components directory
external_components:
  - source:
      type: local
      path: components
    components: [ opentherm ]

# Dashboard web UI
web_server:
  port: 80

# Empty platform declarations (required by ESPHome core)
# Real sensors are defined below in opentherm component
binary_sensor:
sensor:
climate:

# OpenTherm component configuration
opentherm:
  id: opentherm_gateway
  # Pin configuration (for ESP8266/NodeMCU)
  in_pin: 4      # D2 on NodeMCU
  out_pin: 5     # D1 on NodeMCU
  slave_in_pin: 12  # D6 on NodeMCU
  slave_out_pin: 13 # D7 on NodeMCU

  # Binary sensors
  flame:
    name: "${friendly_name} Flame"
    id: boiler_flame

  ch_active:
    name: "${friendly_name} Central Heating"
    id: ch_active

  dhw_active:
    name: "${friendly_name} Hot Water"
    id: dhw_active

  fault:
    name: "${friendly_name} Fault"
    id: boiler_fault

  diagnostic:
    name: "${friendly_name} Diagnostic"
    id: boiler_diagnostic

  # Temperature and other sensors
  external_temperature:
    name: "${friendly_name} External Temperature"

  return_temperature:
    name: "${friendly_name} Return Temperature"

  boiler_temperature:
    name: "${friendly_name} Boiler Temperature"

  pressure:
    name: "${friendly_name} Pressure"

  modulation:
    name: "${friendly_name} Modulation"

  heating_target_temperature:
    name: "${friendly_name} Heating Target Temperature"

  # Phase 1 - Boiler Limits & Diagnostics
  max_ch_setpoint:
    name: "${friendly_name} Max CH Setpoint"

  max_modulation:
    name: "${friendly_name} Max Modulation"

  oem_fault_code:
    name: "${friendly_name} OEM Fault Code"

  oem_diagnostic_code:
    name: "${friendly_name} OEM Diagnostic Code"

  master_ot_version:
    name: "${friendly_name} Master OT Version"

  slave_ot_version:
    name: "${friendly_name} Slave OT Version"

  # Climate entities
  hot_water_climate:
    name: "${friendly_name} Hot Water"

  heating_water_climate:
    name: "${friendly_name} Heating Water"

# Add buttons
button:
  - platform: restart
    name: "${friendly_name} Restart ESP"
    id: restart_button

  # Boiler reset button (BLOR command)
  - platform: opentherm
    opentherm_id: opentherm_gateway
    name: "${friendly_name} Reset Boiler"
    id: reset_boiler_button
    icon: "mdi:restart-alert"
